# each step is defined as one tool call
max_step: 20
sync_tools: 
  - name: wait_tool
    description: |
      Use this tool to wait for you action to take effect. The upper limit is 120 seconds. 
          Any value above 120 seconds will be truncated to 120 seconds. If you call this tool
          along with other tools in your tool_calls list, this tool will be scheduled to the 
          last for execution.

          Args:
              seconds (int): Number of seconds to wait.
async_tools:
  - name: rollback_command
    description: |
      Use this function to roll back the last kubectl command you observed
      When you call this tool multiple times, you will roll-back previous commands in the reverse order of their prior execution."
  - name: get_previous_rollbackable_cmd
    description: |
      Use this function to get a list of commands you previously executed that could be roll-backed.
  - name: r_submit_tool
    description: |
      The tool to submit after you rolled back all the changes.
prompts_path: rollback_agent_prompts.yaml